// Auto-generated by scripts/gen_parity_tests.py from docs/runtime-parity.md.
// Module: node:vm
// This file is a byte-for-byte parity test against `node --experimental-strip-types`.
// Edit the TODO lines below to exercise each API; rerun
// `./run_parity_tests.sh --filter test_parity_vm` to verify.

import * as vm from "node:vm";


// ── Class: vm.Script ──
// TODO(class-member): new vm.Script(code[, options])
// TODO(class-member): script.cachedDataRejected
// TODO(class-member): script.sourceMapURL
// TODO(class-member): script.createCachedData()
// TODO(class-member): script.runInContext(contextifiedObject[, options])
// TODO(class-member): script.runInNewContext([contextObject[, options]])
// TODO(class-member): script.runInThisContext([options])

// ── Class: vm.Module ──
// SKIP: module.error — Experimental VM module state remains gated/open (#3132).
// SKIP: module.identifier — Experimental VM module state remains gated/open (#3132).
// SKIP: module.namespace — Experimental VM module namespace remains gated/open (#3132).
// SKIP: module.status — Experimental VM module state remains gated/open (#3132).
// SKIP: module.evaluate([options]) — Experimental VM module evaluation remains gated/open (#3132).
// SKIP: module.link(linker) — Experimental VM module linking remains gated/open (#3132).

// ── Class: vm.SourceTextModule ──
// SKIP: new vm.SourceTextModule(code[, options]) — Experimental VM module constructor remains gated/open (#3132).
// SKIP: dependencySpecifiers — SourceTextModule dependency metadata remains gated/open (#3322).
// SKIP: moduleRequests — SourceTextModule module request helpers remain gated/open (#3322).
// TODO(class-member): createCachedData()
// SKIP: hasAsyncGraph() — SourceTextModule graph helper remains gated/open (#3132).
// SKIP: hasTopLevelAwait() — SourceTextModule graph helper remains gated/open (#3132).
// SKIP: instantiate() — SourceTextModule instantiation remains gated/open (#3132).
// SKIP: linkRequests(modules) — SourceTextModule request linking remains gated/open (#3132/#3322).

// ── Class: vm.SyntheticModule ──
// SKIP: new vm.SyntheticModule(exportNames, evaluateCallback[, options]) — Experimental SyntheticModule constructor remains gated/open (#3133).
// SKIP: setExport(name, value) — SyntheticModule export mutation remains gated/open (#3133).

// ── Functions ──
// TODO(call): vm.createContext([contextObject[, options]])
// TODO(call): vm.isContext(object)
// TODO(call): vm.runInContext(code, contextifiedObject[, options])
// TODO(call): vm.runInNewContext(code[, contextObject[, options]])
// TODO(call): vm.runInThisContext(code[, options])
// TODO(call): vm.compileFunction(code[, params[, options]])
// SKIP: vm.measureMemory([options]) — V8 heap measurement remains open/inapplicable (#3284).

// ── Constants ──
console.log("vm.constants.USE_MAIN_CONTEXT_DEFAULT_LOADER:", vm.constants.USE_MAIN_CONTEXT_DEFAULT_LOADER);
console.log("vm.constants.DONT_CONTEXTIFY:", vm.constants.DONT_CONTEXTIFY);

// Coverage: 2 auto-emitted, 14 TODO, 16 skip-listed.
